### ISSUE TITLE
HMAC & IP ranges check

### ISSUE THREAD

**Issue by IgorDuino** [garpixcms/garpix_cloudpayments#4]
Если я правильно понял нет никакой проверки HMAC? То есть узнав параметры выставленного счета любой пользователь сможет отправить POSTзапрос и засчитать себе оплату?

Я надеюсь я ошибаюсь, проясните пожалуйста
https://developers.cloudpayments.ru/#proverka-uvedomleniy

**Comment by griviala** [comment]
Исправлено в https://github.com/garpixcms/garpix_cloudpayments/pull/5

**Comment by IgorDuino** [comment]
ничего себе у вас рефакторинг......

**Comment by AnatolyBur** [comment]
> ничего себе у вас рефакторинг......

Давно хотели) 
Спасибо за issue.
